Writting first set of initial tests
Pedja92/Vivify-Scrum pull request #1
Opened 2022-05-18 22:01 UTC by Pedja92

2022-05-19 19:46 UTC, bdimitrovski requested changes
Overall fine, but please correct these few minor details.

2022-05-19 19:46 UTC, bdimitrovski commented on .gitignore
> +/node_modules
newline

2022-05-19 19:46 UTC, bdimitrovski commented on cypress/fixtures/example.json
> +}
This file is not needed at all, please remove it.

2022-05-19 19:46 UTC, bdimitrovski commented on cypress/integration/board.spec.js
> +  beforeEach(() => {
We should not use hooks yet, but kudos for trying ;) Remove them for now.

2022-05-19 19:46 UTC, bdimitrovski commented on cypress/integration/board.spec.js
> +  });
Please make some whitespace between the tests, it will look much nicer.

2022-05-19 19:46 UTC, bdimitrovski commented on cypress/integration/board.spec.js
> +  //   });
Is this needed? If not, please remove.

2022-05-19 19:46 UTC, bdimitrovski commented on cypress/integration/login.spec.js
> +    cy.visit("baseUrl");
Should these be `cy.visit("baseUrl")` or `cy.visit(Cypress.config(baseUrl))`?

2022-05-26 07:26 UTC, andrija989 requested changes
- sve konstante prebaci u data
- sve lokatore u pom
- mislim da ti nije dobra implementacija cy.visit(), treba da koristis nacin koji ti je bojan napisao

2022-05-26 07:26 UTC, andrija989 commented on cypress/integration/board.spec.js
> +    cy.get(login.passwordInputField).type("03091992");
pomeri testne podatke u data

2022-05-26 07:26 UTC, andrija989 commented on cypress/integration/board.spec.js
> +      .should("be.visible")
pomeri lokatore gde im je mesto u pom

2022-05-26 07:26 UTC, andrija989 commented on cypress/integration/board.spec.js
> +  it.only("Archive board", () => {
uvek skloni .only kada prebacis stvari na git... da ne bi zaboravio na ovaj deo i vrteo ti se samo 1 test

2022-05-30 20:55 UTC, merged